### ISSUE TITLE
Ship decor arn't free. Is this a bug?

### ISSUE THREAD

**Issue by eco8011** [7PH/free-ship-decorations-lethal-company-mod#1]
![image](https://github.com/7PH/free-ship-decorations-lethal-company-mod/assets/157389317/8a99e324-6520-4d13-83ad-eef9c14bdc4a)
idk why, but like 90% of decorations aren't free(sorry for my eng if i bad)

**Comment by eco8011** [comment]
(original decorations)

**Comment by 7PH** [comment]
Hey there, are you using another mod simultaneously? (So I can check your setup)

With the latest version of this mod, you are supposed to see:
- Only one ship decoration available
- It should be free

So I'm a bit confused that you are seeing that many!

**Comment by eco8011** [comment]
shit, I misunderstood what this mod does. thats my fault. But i think that unlock all decorations at once will be better, than 1 per quota. this is only my opinion, i'm not urge

**Comment by 7PH** [comment]
You know what? I think you're right 😁 

I've modified this mod so that it:
- Makes all ship decoration availables in the store
- Makes all ship decoration free

I moved the previous use-case (single ship decoration per rotation for free) to another repository, [here](https://github.com/7PH/free-single-ship-decorations-lethal-company-mod)

So, feel free to update this mod to [`v1.2.0`](https://thunderstore.io/c/lethal-company/p/7PH/Free_Ship_Decorations/) to get what you want.
- [Thunderstore link](https://thunderstore.io/c/lethal-company/p/7PH/Free_Ship_Decorations/)
- [Github release link](https://github.com/7PH/free-ship-decorations-lethal-company-mod/releases/tag/v1.2.0)

Thanks for the feedback.

**Comment by 7PH** [comment]
I'm closing this issue as what you need is now implemented
